### ISSUE TITLE
i dont understand lol

### ISSUE THREAD

**Issue by dvvvsh** [Sector443/eth_keyfun#2]
Traceback (most recent call last):
  File "/Users/jonathandoe/eth_keyfun/eth_keyfun.py", line 131, in <module>
    x.linear_brute(args.eth_address)
  File "/Users/jonathandoe/eth_keyfun/eth_keyfun.py", line 55, in linear_brute
    pk = keys.PrivateKey(key)
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/site-packages/eth_keys/datatypes.py", line 255, in __init__
    self.public_key = self.backend.private_key_to_public_key(self)
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/site-packages/eth_keys/backends/coincurve.py", line 109, in private_key_to_public_key
    public_key_bytes = self.keys.PrivateKey(private_key.to_bytes()).public_key.format(
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/site-packages/coincurve/keys.py", line 31, in __init__
    self.secret: bytes = validate_secret(secret) if secret is not None else get_valid_secret()
  File "/Users/jonathandoe/opt/anaconda3/lib/python3.9/site-packages/coincurve/utils.py", line 91, in validate_secret
    raise ValueError('Secret scalar must be greater than 0 and less than {}.'.format(GROUP_ORDER_INT))
ValueError: Secret scalar must be greater than 0 and less than 115792089237316195423570985008687907852837564279074904382605163141518161494337.
jonathandoe@MacBook-Air-3 eth_keyfun %

**Comment by cougarbytes** [comment]
Something must have changed in recent python 3.9 I remember writing this code around 3.6. I will try to resolve it and see it works or not.
